#include "Country.h"


String Country::toString()
{
    String result = alphaCode;
    result = result + "("+ code +") - "+ longName;
    return result; 
}

void Country::setValues(int code, String alphaCode, String longName, String shortName)
{
    this->code = code;
    this->alphaCode = alphaCode;
    this->longName = longName;
    this->shortName = shortName;
}

Country Country::getCountry(int code)
{
    Country result;
    switch(code)
    {
        case	501	 : result.setValues(501	,F("ADE"),F("Adelie Land"),F("AdelieLand"));break;
        case	201	 : result.setValues(201	,F("ALB"),F("Albania"),F("Albania"));break;
        case	202	 : result.setValues(202	,F("AND"),F("Andorra"),F("Andorra"));break;
        case	203	 : result.setValues(203	,F("AUT"),F("Austria"),F("Austria"));break;
        case	204	 : result.setValues(204	,F("AZC"),F("Azores"),F("Azores"));break;
        case	205	 : result.setValues(205	,F("BEL"),F("Belgium"),F("Belgium"));break;
        case	206	 : result.setValues(206	,F("BLR"),F("Belarus"),F("Belarus"));break;
        case	207	 : result.setValues(207	,F("BUL"),F("Bulgaria"),F("Bulgaria"));break;
        case	208	 : result.setValues(208	,F("VAT"),F("Vatican City State"),F("Vatican"));break;
        case	209	 : result.setValues(209	,F("CYP"),F("Cyprus"),F("Cyprus"));break;
        case	210	 : result.setValues(210	,F("CYP"),F("Cyprus"),F("Cyprus"));break;
        case	211	 : result.setValues(211	,F("GER"),F("Germany"),F("Germany"));break;
        case	212	 : result.setValues(212	,F("CYP"),F("Cyprus"),F("Cyprus"));break;
        case	213	 : result.setValues(213	,F("GOG"),F("Georgia"),F("Georgia"));break;
        case	214	 : result.setValues(214	,F("MOL"),F("Moldova"),F("Moldova"));break;
        case	215	 : result.setValues(215	,F("MAL"),F("Malta"),F("MALTA"));break;
        case	216	 : result.setValues(216	,F("ARM"),F("Armenia"),F("Armenia"));break;
        case	218	 : result.setValues(218	,F("GER"),F("Germany"),F("Germany"));break;
        case	219	 : result.setValues(219	,F("DEN"),F("Denmark"),F("Denmark"));break;
        case	220	 : result.setValues(220	,F("DEN"),F("Denmark"),F("Denmark"));break;
        case	224	 : result.setValues(224	,F("SPA"),F("Spain"),F("Spain"));break;
        case	225	 : result.setValues(225	,F("SPA"),F("Spain"),F("Spain"));break;
        case	226	 : result.setValues(226	,F("FRA"),F("France"),F("France"));break;
        case	227	 : result.setValues(227	,F("FRA"),F("France"),F("France"));break;
        case	228	 : result.setValues(228	,F("FRA"),F("France"),F("France"));break;
        case	229	 : result.setValues(229	,F("MAL"),F("Malta"),F("Malta"));break;
        case	230	 : result.setValues(230	,F("FIN"),F("Finland"),F("Finland"));break;
        case	231	 : result.setValues(231	,F("FAR"),F("Faroe Islands"),F("Faro Isle"));break;
        case	232	 : result.setValues(232	,F("UKM"),F("United Kingdom"),F("G Britain"));break;
        case	233	 : result.setValues(233	,F("UKM"),F("United Kingdom"),F("G Britain"));break;
        case	234	 : result.setValues(234	,F("UKM"),F("United Kingdom"),F("G Britain"));break;
        case	235	 : result.setValues(235	,F("UKM"),F("United Kingdom"),F("G Britain"));break;
        case	236	 : result.setValues(236	,F("GIB"),F("Gibraltar"),F("Gibraltar"));break;
        case	237	 : result.setValues(237	,F("GRE"),F("Greece"),F("Greece"));break;
        case	238	 : result.setValues(238	,F("CRT"),F("Croatia"),F("Croatia"));break;
        case	239	 : result.setValues(239	,F("GRE"),F("Greece"),F("Greece"));break;
        case	240	 : result.setValues(240	,F("GRE"),F("Greece"),F("Greece"));break;
        case	241	 : result.setValues(241	,F("GRE"),F("Greece"),F("Greece"));break;
        case	242	 : result.setValues(242	,F("MOR"),F("Morocco"),F("Morocco"));break;
        case	243	 : result.setValues(243	,F("HUN"),F("Hungary"),F("Hungary"));break;
        case	244	 : result.setValues(244	,F("NET"),F("Netherlands"),F("Netherland"));break;
        case	245	 : result.setValues(245	,F("NET"),F("Netherlands"),F("Netherland"));break;
        case	246	 : result.setValues(246	,F("NET"),F("Netherlands"),F("Netherland"));break;
        case	247	 : result.setValues(247	,F("ITA"),F("Italy"),F("Italy"));break;
        case	248	 : result.setValues(248	,F("MAL"),F("Malta"),F("Malta"));break;
        case	249	 : result.setValues(249	,F("MAL"),F("Malta"),F("Malta"));break;
        case	250	 : result.setValues(250	,F("IRE"),F("Ireland"),F("Ireland"));break;
        case	251	 : result.setValues(251	,F("ICE"),F("Iceland"),F("Iceland"));break;
        case	252	 : result.setValues(252	,F("LIE"),F("Liechtenstein"),F("Liechten"));break;
        case	253	 : result.setValues(253	,F("LUX"),F("Luxembourg"),F("Luxembourg"));break;
        case	254	 : result.setValues(254	,F("MON"),F("Monaco"),F("Monaco"));break;
        case	255	 : result.setValues(255	,F("MAE"),F("Madeira"),F("Madeira"));break;
        case	256	 : result.setValues(256	,F("MAL"),F("Malta"),F("Malta"));break;
        case	257	 : result.setValues(257	,F("NOR"),F("Norway"),F("Norway"));break;
        case	258	 : result.setValues(258	,F("NOR"),F("Norway"),F("Norway"));break;
        case	259	 : result.setValues(259	,F("NOR"),F("Norway"),F("Norway"));break;
        case	261	 : result.setValues(261	,F("POL"),F("Poland"),F("Poland"));break;
        case	262	 : result.setValues(262	,F("MNT"),F("Montenegro"),F("Montenegro"));break;
        case	263	 : result.setValues(263	,F("POR"),F("Portugal"),F("Portugal"));break;
        case	264	 : result.setValues(264	,F("ROM"),F("Romania"),F("Romania"));break;
        case	265	 : result.setValues(265	,F("SWE"),F("Sweden"),F("Sweden"));break;
        case	266	 : result.setValues(266	,F("SWE"),F("Sweden"),F("Sweden"));break;
        case	267	 : result.setValues(267	,F("SLV"),F("Slovak Republic"),F("Slovakia"));break;
        case	268	 : result.setValues(268	,F("SAN"),F("San Marino"),F("San Marino"));break;
        case	269	 : result.setValues(269	,F("SWT"),F("Switzerland"),F("Swiss"));break;
        case	270	 : result.setValues(270	,F("CZH"),F("Czech Republic"),F("Czech Rep"));break;
        case	271	 : result.setValues(271	,F("TUR"),F("TÃƒÂ¼rkiye"),F("TÃƒÂ¼rkiye"));break;
        case	272	 : result.setValues(272	,F("UKR"),F("Ukraine"),F("Ukraine"));break;
        case	273	 : result.setValues(273	,F("RUS"),F("Russian Federation"),F("Russia"));break;
        case	274	 : result.setValues(274	,F("MKD"),F("North Macedonia (Republic of)"),F("North Mac"));break;
        case	275	 : result.setValues(275	,F("LAT"),F("Latvia"),F("Latvia"));break;
        case	276	 : result.setValues(276	,F("EST"),F("Estonia"),F("Estonia"));break;
        case	277	 : result.setValues(277	,F("LIT"),F("Lithuania"),F("Lithuania"));break;
        case	278	 : result.setValues(278	,F("SVN"),F("Slovenia"),F("Slovenia"));break;
        case	279	 : result.setValues(279	,F("SER"),F("Serbia"),F("Serbia"));break;
        case	301	 : result.setValues(301	,F("ANA"),F("Anguilla"),F("Anguilla"));break;
        case	303	 : result.setValues(303	,F("ALA"),F("Alaska (State of)"),F("Alaska"));break;
        case	304	 : result.setValues(304	,F("ANT"),F("Antigua and Barbuda"),F("Antigua"));break;
        case	305	 : result.setValues(305	,F("ANT"),F("Antigua and Barbuda"),F("Antigua"));break;
        case	306	 : result.setValues(306	,F("NEA"),F("Netherlands Antilles"),F("N Antilles"));break;
        case	307	 : result.setValues(307	,F("ARU"),F("Aruba"),F("Aruba"));break;
        case	308	 : result.setValues(308	,F("BAA"),F("Bahamas"),F("Bahamas"));break;
        case	309	 : result.setValues(309	,F("BAA"),F("Bahamas"),F("Bahamas"));break;
        case	310	 : result.setValues(310	,F("BER"),F("Bermuda"),F("Bermuda"));break;
        case	311	 : result.setValues(311	,F("BAA"),F("Bahamas"),F("Bahamas"));break;
        case	312	 : result.setValues(312	,F("BEZ"),F("Belize"),F("Belize"));break;
        case	314	 : result.setValues(314	,F("BAR"),F("Barbados"),F("Barbados"));break;
        case	316	 : result.setValues(316	,F("CAN"),F("Canada"),F("Canada"));break;
        case	319	 : result.setValues(319	,F("CAY"),F("Cayman Islands"),F("Cayman Is"));break;
        case	321	 : result.setValues(321	,F("COS"),F("Costa Rica"),F("Costa Rica"));break;
        case	323	 : result.setValues(323	,F("CUB"),F("Cuba"),F("Cuba"));break;
        case	325	 : result.setValues(325	,F("DOM"),F("Dominica"),F("Dominica"));break;
        case	327	 : result.setValues(327	,F("DOR"),F("Dominican Republic"),F("Dominican"));break;
        case	329	 : result.setValues(329	,F("GUA"),F("Guadeloupe"),F("Guadeloupe"));break;
        case	330	 : result.setValues(330	,F("GRA"),F("Grenada"),F("Grenada"));break;
        case	331	 : result.setValues(331	,F("GRN"),F("Greenland"),F("Greenland"));break;
        case	332	 : result.setValues(332	,F("GUT"),F("Guatemala"),F("Guatemala"));break;
        case	334	 : result.setValues(334	,F("HON"),F("Honduras"),F("Honduras"));break;
        case	336	 : result.setValues(336	,F("HAI"),F("Haiti"),F("Haiti"));break;
        case	338	 : result.setValues(338	,F("USA"),F("United States"),F("USA"));break;
        case	339	 : result.setValues(339	,F("JAM"),F("Jamaica"),F("Jamaica"));break;
        case	341	 : result.setValues(341	,F("SKN"),F("Saint Kitts and Nevis"),F("St Kitts"));break;
        case	343	 : result.setValues(343	,F("SLU"),F("Saint Lucia"),F("St Lucia"));break;
        case	345	 : result.setValues(345	,F("MEX"),F("Mexico"),F("Mexico"));break;
        case	347	 : result.setValues(347	,F("MTQ"),F("Martinique"),F("Martinique"));break;
        case	348	 : result.setValues(348	,F("MOT"),F("Montserrat"),F("Montserrat"));break;
        case	350	 : result.setValues(350	,F("NIC"),F("Nicaragua"),F("Nicaragua"));break;
        case	351	 : result.setValues(351	,F("PAN"),F("Panama"),F("Panama"));break;
        case	352	 : result.setValues(352	,F("PAN"),F("Panama"),F("Panama"));break;
        case	353	 : result.setValues(353	,F("PAN"),F("Panama"),F("Panama"));break;
        case	354	 : result.setValues(354	,F("PAN"),F("Panama"),F("Panama"));break;
        case	355	 : result.setValues(355	,F("PAN"),F("Panama"),F("Panama"));break;
        case	356	 : result.setValues(356	,F("PAN"),F("Panama"),F("Panama"));break;
        case	357	 : result.setValues(357	,F("PAN"),F("Panama"),F("Panama"));break;
        case	358	 : result.setValues(358	,F("PUE"),F("Puerto Rico"),F("PuertoRico"));break;
        case	359	 : result.setValues(359	,F("ELS"),F("El Salvador"),F("ElSalvador"));break;
        case	361	 : result.setValues(361	,F("SPI"),F("St. Pierre and Miquelon"),F("St Pierre"));break;
        case	362	 : result.setValues(362	,F("TAT"),F("Trinidad and Tobago"),F("Trinidad"));break;
        case	364	 : result.setValues(364	,F("TUK"),F("Turks and Caicos Islands"),F("Caicos Is"));break;
        case	366	 : result.setValues(366	,F("USA"),F("United States"),F("USA"));break;
        case	367	 : result.setValues(367	,F("USA"),F("United States"),F("USA"));break;
        case	368	 : result.setValues(368	,F("USA"),F("United States"),F("USA"));break;
        case	369	 : result.setValues(369	,F("USA"),F("United States"),F("USA"));break;
        case	370	 : result.setValues(370	,F("PAN"),F("Panama"),F("Panama"));break;
        case	371	 : result.setValues(371	,F("PAN"),F("Panama"),F("Panama"));break;
        case	372	 : result.setValues(372	,F("PAN"),F("Panama"),F("Panama"));break;
        case	373	 : result.setValues(373	,F("PAN"),F("Panama"),F("Panama"));break;
        case	374	 : result.setValues(374	,F("PAN"),F("Panama"),F("Panama"));break;
        case	375	 : result.setValues(375	,F("SVG"),F("Saint Vincent and the Grenadines"),F("St Vincent"));break;
        case	376	 : result.setValues(376	,F("SVG"),F("Saint Vincent and the Grenadines"),F("St Vincent"));break;
        case	377	 : result.setValues(377	,F("SVG"),F("Saint Vincent and the Grenadines"),F("St Vincent"));break;
        case	378	 : result.setValues(378	,F("BVI"),F("British Virgin Islands"),F("Virgin GB"));break;
        case	379	 : result.setValues(379	,F("USV"),F("United States Virgin Islands"),F("Virgin US"));break;
        case	401	 : result.setValues(401	,F("AFG"),F("Afghanistan"),F("Afghan"));break;
        case	403	 : result.setValues(403	,F("SAU"),F("Saudi Arabia"),F("Saudi"));break;
        case	405	 : result.setValues(405	,F("BAN"),F("Bangladesh"),F("Bangladesh"));break;
        case	408	 : result.setValues(408	,F("BAH"),F("Bahrain"),F("Bahrain"));break;
        case	410	 : result.setValues(410	,F("BHU"),F("Bhutan"),F("Bhutan"));break;
        case	412	 : result.setValues(412	,F("CHN"),F("China"),F("China"));break;
        case	413	 : result.setValues(413	,F("CHN"),F("China"),F("China"));break;
        case	414	 : result.setValues(414	,F("CHN"),F("China"),F("CHINA"));break;
        case	416	 : result.setValues(416	,F("TAI"),F("Chinese Taipei"),F("Taipei"));break;
        case	417	 : result.setValues(417	,F("SRI"),F("Sri Lanka"),F("Sri Lanka"));break;
        case	419	 : result.setValues(419	,F("IND"),F("India"),F("India"));break;
        case	422	 : result.setValues(422	,F("IRN"),F("Iran"),F("Iran"));break;
        case	423	 : result.setValues(423	,F("AZR"),F("Azerbaijan"),F("Azerbaijan"));break;
        case	425	 : result.setValues(425	,F("IRQ"),F("Iraq"),F("Iraq"));break;
        case	428	 : result.setValues(428	,F("ISR"),F("Israel"),F("Israel"));break;
        case	431	 : result.setValues(431	,F("JPN"),F("Japan"),F("Japan"));break;
        case	432	 : result.setValues(432	,F("JPN"),F("Japan"),F("Japan"));break;
        case	434	 : result.setValues(434	,F("TKM"),F("Turkmenistan"),F("Turkmenist"));break;
        case	436	 : result.setValues(436	,F("KAZ"),F("Kazakhstan"),F("Kazakhstan"));break;
        case	437	 : result.setValues(437	,F("UZB"),F("Uzbekistan"),F("Uzbekistan"));break;
        case	438	 : result.setValues(438	,F("JOR"),F("Jordan"),F("Jordan"));break;
        case	440	 : result.setValues(440	,F("KOR"),F("Korea (Republic of)"),F("Korea Sou"));break;
        case	441	 : result.setValues(441	,F("KOR"),F("Korea (Republic of)"),F("Korea Sou"));break;
        case	443	 : result.setValues(443	,F("PAA"),F("Palestine"),F("Palestine"));break;
        case	445	 : result.setValues(445	,F("KDR"),F("Democratic People's Republic of Korea"),F("Korea Nor"));break;
        case	447	 : result.setValues(447	,F("KUW"),F("Kuwait"),F("Kuwait"));break;
        case	450	 : result.setValues(450	,F("LEB"),F("Lebanon"),F("Lebanon"));break;
        case	451	 : result.setValues(451	,F("KYR"),F("Kyrgyz Republic"),F("Kyrgyzia"));break;
        case	453	 : result.setValues(453	,F("MAC"),F("Macao, China"),F("Macao"));break;
        case	455	 : result.setValues(455	,F("MAV"),F("Maldives"),F("Maldives"));break;
        case	457	 : result.setValues(457	,F("MNG"),F("Mongolia"),F("Mongolia"));break;
        case	459	 : result.setValues(459	,F("NEP"),F("Nepal"),F("Nepal"));break;
        case	461	 : result.setValues(461	,F("OMN"),F("Oman"),F("Oman"));break;
        case	463	 : result.setValues(463	,F("PAK"),F("Pakistan"),F("Pakistan"));break;
        case	466	 : result.setValues(466	,F("QAT"),F("Qatar"),F("Qatar"));break;
        case	468	 : result.setValues(468	,F("SYR"),F("Syria"),F("Syria"));break;
        case	470	 : result.setValues(470	,F("UAE"),F("United Arab Emirates"),F("UAE"));break;
        case	471	 : result.setValues(471	,F("UAE"),F("United Arab Emirates"),F("UAE"));break;
        case	472	 : result.setValues(472	,F("TJK"),F("Tajikistan"),F("TAJIKISTAN"));break;
        case	473	 : result.setValues(473	,F("YEM"),F("Yemen"),F("Yemen"));break;
        case	475	 : result.setValues(475	,F("YEM"),F("Yemen"),F("Yemen"));break;
        case	477	 : result.setValues(477	,F("HKG"),F("Hong Kong, China"),F("Hong Kong"));break;
        case	478	 : result.setValues(478	,F("BOS"),F("Bosnia and Herzegovina"),F("Bosniaherz"));break;
        case	503	 : result.setValues(503	,F("AUS"),F("Australia"),F("Australia"));break;
        case	506	 : result.setValues(506	,F("BUR"),F("Myanmar"),F("Burma"));break;
        case	508	 : result.setValues(508	,F("BRU"),F("Brunei Darussalam"),F("Brunei"));break;
        case	510	 : result.setValues(510	,F("MIC"),F("Micronesia"),F("Micronesia"));break;
        case	511	 : result.setValues(511	,F("PAL"),F("Palau"),F("Palau"));break;
        case	512	 : result.setValues(512	,F("NZL"),F("New Zealand"),F("NewZealand"));break;
        case	514	 : result.setValues(514	,F("CMB"),F("Cambodia"),F("Cambodia"));break;
        case	515	 : result.setValues(515	,F("CMB"),F("Cambodia"),F("Cambodia"));break;
        case	516	 : result.setValues(516	,F("CHR"),F("Christmas Island"),F("Christmas"));break;
        case	518	 : result.setValues(518	,F("COO"),F("Cook Islands"),F("Cook Isles"));break;
        case	520	 : result.setValues(520	,F("FIJ"),F("Fiji"),F("Fiji"));break;
        case	523	 : result.setValues(523	,F("COC"),F("Cocos (Keeling) Islands"),F("Cocos Isle"));break;
        case	525	 : result.setValues(525	,F("INO"),F("Indonesia"),F("Indonesia"));break;
        case	529	 : result.setValues(529	,F("KIR"),F("Kiribati"),F("Kiribati"));break;
        case	531	 : result.setValues(531	,F("LAO"),F("Laos"),F("Lao"));break;
        case	533	 : result.setValues(533	,F("MLY"),F("Malaysia"),F("Malaysia"));break;
        case	536	 : result.setValues(536	,F("MAI"),F("Northern Mariana Islands"),F("Mariana Is"));break;
        case	538	 : result.setValues(538	,F("MAR"),F("Marshall Islands"),F("Marshall I"));break;
        case	540	 : result.setValues(540	,F("NCA"),F("New Caledonia"),F("Caledonia"));break;
        case	542	 : result.setValues(542	,F("NIU"),F("Niue"),F("Niue Isle"));break;
        case	544	 : result.setValues(544	,F("NAU"),F("Nauru"),F("Nauru"));break;
        case	546	 : result.setValues(546	,F("PLY"),F("French Polynesia"),F("Polynesia"));break;
        case	548	 : result.setValues(548	,F("PHI"),F("Philippines"),F("Philippine"));break;
        case	550	 : result.setValues(550	,F("TIM"),F("Timor-Leste (Democratic Republic of)"),F("TimorLeste"));break;
        case	553	 : result.setValues(553	,F("PAP"),F("Papua New Guinea"),F("Papua NG"));break;
        case	555	 : result.setValues(555	,F("PIT"),F("Pitcairn"),F("Pitcairn I"));break;
        case	557	 : result.setValues(557	,F("SOL"),F("Solomon Islands"),F("Solomon Is"));break;
        case	559	 : result.setValues(559	,F("ASA"),F("American Samoa"),F("Samoa USA"));break;
        case	561	 : result.setValues(561	,F("WSA"),F("Samoa"),F("West Samoa"));break;
        case	563	 : result.setValues(563	,F("SIN"),F("Singapore"),F("Singapore"));break;
        case	564	 : result.setValues(564	,F("SIN"),F("Singapore"),F("Singapore"));break;
        case	565	 : result.setValues(565	,F("SIN"),F("Singapore"),F("Singapore"));break;
        case	566	 : result.setValues(566	,F("SIN"),F("Singapore"),F("SINGAPORE"));break;
        case	567	 : result.setValues(567	,F("THA"),F("Thailand"),F("Thailand"));break;
        case	570	 : result.setValues(570	,F("TON"),F("Tonga"),F("Tonga"));break;
        case	572	 : result.setValues(572	,F("TUV"),F("Tuvalu"),F("Tuvalu Is"));break;
        case	574	 : result.setValues(574	,F("VIE"),F("Vietnam"),F("Vietnam"));break;
        case	576	 : result.setValues(576	,F("VAN"),F("Vanuatu"),F("Vanuatu"));break;
        case	577	 : result.setValues(577	,F("VAN"),F("Vanuatu"),F("Vanuatu"));break;
        case	578	 : result.setValues(578	,F("WAL"),F("Wallis and Futuna Islands"),F("Wallis Is"));break;
        case	601	 : result.setValues(601	,F("SAF"),F("South Africa"),F("So Africa"));break;
        case	603	 : result.setValues(603	,F("ANG"),F("Angola"),F("Angola"));break;
        case	605	 : result.setValues(605	,F("ALG"),F("Algeria"),F("Algeria"));break;
        case	607	 : result.setValues(607	,F("SPL"),F("Saint Paul and Amsterdam Islands"),F("St Paul"));break;
        case	608	 : result.setValues(608	,F("ASC"),F("Ascension Island"),F("Ascension"));break;
        case	609	 : result.setValues(609	,F("BUI"),F("Burundi"),F("Burundi"));break;
        case	610	 : result.setValues(610	,F("BEN"),F("Benin"),F("Benin"));break;
        case	611	 : result.setValues(611	,F("BOT"),F("Botswana"),F("Botswana"));break;
        case	612	 : result.setValues(612	,F("CAR"),F("Central African Republic"),F("CenAfr Rep"));break;
        case	613	 : result.setValues(613	,F("CAM"),F("Cameroon"),F("Cameroon"));break;
        case	615	 : result.setValues(615	,F("CON"),F("Congo"),F("Congo"));break;
        case	616	 : result.setValues(616	,F("COM"),F("Comoros"),F("Comoros"));break;
        case	617	 : result.setValues(617	,F("CAP"),F("Cape Verde"),F("Cape Verde"));break;
        case	618	 : result.setValues(618	,F("CRP"),F("Crozet Archipelago"),F("Crozet"));break;
        case	619	 : result.setValues(619	,F("IVO"),F("Ivory Coast"),F("IvoryCoast"));break;
        case	620	 : result.setValues(620	,F("COM"),F("Comoros"),F("Comoros"));break;
        case	621	 : result.setValues(621	,F("DJI"),F("Djibouti"),F("Djibouti"));break;
        case	622	 : result.setValues(622	,F("EGY"),F("Egypt"),F("Egypt"));break;
        case	624	 : result.setValues(624	,F("ETH"),F("Ethiopia"),F("Ethiopia"));break;
        case	625	 : result.setValues(625	,F("ERT"),F("Eritrea"),F("Eritrea"));break;
        case	626	 : result.setValues(626	,F("GAB"),F("Gabon"),F("Gabon Rep"));break;
        case	627	 : result.setValues(627	,F("GHA"),F("Ghana"),F("Ghana"));break;
        case	629	 : result.setValues(629	,F("GAM"),F("Gambia"),F("Gambia"));break;
        case	630	 : result.setValues(630	,F("GUB"),F("Guinea-Bissau"),F("Guinea Bis"));break;
        case	631	 : result.setValues(631	,F("EQG"),F("Equatorial Guinea"),F("Eq Guinea"));break;
        case	632	 : result.setValues(632	,F("GUN"),F("Guinea"),F("Guinea Rep"));break;
        case	633	 : result.setValues(633	,F("BUF"),F("Burkina Faso"),F("Burkina FS"));break;
        case	634	 : result.setValues(634	,F("KEN"),F("Kenya"),F("Kenya"));break;
        case	635	 : result.setValues(635	,F("KER"),F("Kerguelen Islands"),F("Kerguelen"));break;
        case	636	 : result.setValues(636	,F("LIB"),F("Liberia"),F("Liberia"));break;
        case	637	 : result.setValues(637	,F("LIB"),F("Liberia"),F("Liberia"));break;
        case	638	 : result.setValues(638	,F("SSD"),F("South Sudan"),F("Southsudan"));break;
        case	642	 : result.setValues(642	,F("LBY"),F("Libya"),F("Libya"));break;
        case	644	 : result.setValues(644	,F("LES"),F("Lesotho"),F("Lesotho"));break;
        case	645	 : result.setValues(645	,F("MAU"),F("Mauritius"),F("Mauritius"));break;
        case	647	 : result.setValues(647	,F("MAD"),F("Madagascar"),F("Madagascar"));break;
        case	649	 : result.setValues(649	,F("MLI"),F("Mali"),F("Mali"));break;
        case	650	 : result.setValues(650	,F("MOZ"),F("Mozambique"),F("Mozambique"));break;
        case	654	 : result.setValues(654	,F("MAA"),F("Mauritania"),F("Mauritania"));break;
        case	655	 : result.setValues(655	,F("MAW"),F("Malawi"),F("Malawi"));break;
        case	656	 : result.setValues(656	,F("NIG"),F("Niger"),F("Niger"));break;
        case	657	 : result.setValues(657	,F("NIA"),F("Nigeria"),F("Nigeria"));break;
        case	659	 : result.setValues(659	,F("NAM"),F("Namibia"),F("Namibia"));break;
        case	660	 : result.setValues(660	,F("REU"),F("Reunion (also same country code for Mayotte)"),F("Reunion"));break;
        case	661	 : result.setValues(661	,F("RWA"),F("Rwanda"),F("Rwanda"));break;
        case	662	 : result.setValues(662	,F("SUD"),F("Sudan"),F("Sudan"));break;
        case	663	 : result.setValues(663	,F("SEN"),F("Senegal"),F("Senegal"));break;
        case	664	 : result.setValues(664	,F("SEY"),F("Seychelles"),F("Seychelle"));break;
        case	665	 : result.setValues(665	,F("SHE"),F("St. Helena"),F("St Helena"));break;
        case	666	 : result.setValues(666	,F("SOM"),F("Somalia"),F("Somali"));break;
        case	667	 : result.setValues(667	,F("SIL"),F("Sierra Leone"),F("Sierra Leo"));break;
        case	668	 : result.setValues(668	,F("SAO"),F("Sao Tome and Principe"),F("Sao Tome"));break;
        case	669	 : result.setValues(669	,F("SWZ"),F("Eswatini"),F("Eswatini"));break;
        case	670	 : result.setValues(670	,F("CHA"),F("Chad"),F("Chad"));break;
        case	671	 : result.setValues(671	,F("TOG"),F("Togo"),F("Togo"));break;
        case	672	 : result.setValues(672	,F("TUN"),F("Tunisia"),F("Tunisia"));break;
        case	674	 : result.setValues(674	,F("TAN"),F("Tanzania"),F("Tanzania"));break;
        case	675	 : result.setValues(675	,F("UGA"),F("Uganda"),F("Uganda"));break;
        case	676	 : result.setValues(676	,F("ZAI"),F("Democratic Republic of the Congo"),F("Zaire"));break;
        case	677	 : result.setValues(677	,F("TAN"),F("Tanzania"),F("Tanzania"));break;
        case	678	 : result.setValues(678	,F("ZAM"),F("Zambia"),F("Zambia"));break;
        case	679	 : result.setValues(679	,F("ZIM"),F("Zimbabwe"),F("Zimbabwe"));break;
        case	701	 : result.setValues(701	,F("ARG"),F("Argentina"),F("Argentina"));break;
        case	710	 : result.setValues(710	,F("BRA"),F("Brazil"),F("Brazil"));break;
        case	720	 : result.setValues(720	,F("BOL"),F("Bolivia"),F("Bolivia"));break;
        case	725	 : result.setValues(725	,F("CHI"),F("Chile"),F("Chile"));break;
        case	730	 : result.setValues(730	,F("COL"),F("Colombia"),F("Colombia"));break;
        case	735	 : result.setValues(735	,F("ECU"),F("Ecuador"),F("Ecuador"));break;
        case	740	 : result.setValues(740	,F("FAL"),F("Falkland Islands (Malvinas)"),F("Falkland I"));break;
        case	745	 : result.setValues(745	,F("GUI"),F("Guiana (French Dept. Of)"),F("Guiana"));break;
        case	750	 : result.setValues(750	,F("GUY"),F("Guyana"),F("Guyana"));break;
        case	755	 : result.setValues(755	,F("PAR"),F("Paraguay"),F("Paraguay"));break;
        case	760	 : result.setValues(760	,F("PER"),F("Peru"),F("Peru"));break;
        case	765	 : result.setValues(765	,F("SUR"),F("Suriname"),F("Suriname"));break;
        case	770	 : result.setValues(770	,F("URU"),F("Uruguay"),F("Uruguay"));break;
        case	775	 : result.setValues(775	,F("VEN"),F("Venezuela"),F("Venezuela"));break;
        default : result.setValues(code,F("UNK"),F("Unknown country"),F("Unkown"));
    }
    return result;
}