#include "Country.h"


String Country::toString()
{
    String result = alphaCode;
    result = result + "("+ code +") - "+ longName;
    return result; 
}

void Country::setValues(int code, const char* alphaCode, const char* longName, const char* shortName)
{
    this->code = code;
    this->alphaCode = alphaCode;
    this->longName = longName;
    this->shortName = shortName;
}

Country Country::getCountry(int code)
{
    Country result;
    switch(code)
    {
        case	501	 : result.setValues(501	,"ADE","Adelie Land","AdelieLand");
        case	201	 : result.setValues(201	,"ALB","Albania","Albania");
        case	202	 : result.setValues(202	,"AND","Andorra","Andorra");
        case	203	 : result.setValues(203	,"AUT","Austria","Austria");
        case	204	 : result.setValues(204	,"AZC","Azores","Azores");
        case	205	 : result.setValues(205	,"BEL","Belgium","Belgium");
        case	206	 : result.setValues(206	,"BLR","Belarus","Belarus");
        case	207	 : result.setValues(207	,"BUL","Bulgaria","Bulgaria");
        case	208	 : result.setValues(208	,"VAT","Vatican City State","Vatican");
        case	209	 : result.setValues(209	,"CYP","Cyprus","Cyprus");
        case	210	 : result.setValues(210	,"CYP","Cyprus","Cyprus");
        case	211	 : result.setValues(211	,"GER","Germany","Germany");
        case	212	 : result.setValues(212	,"CYP","Cyprus","Cyprus");
        case	213	 : result.setValues(213	,"GOG","Georgia","Georgia");
        case	214	 : result.setValues(214	,"MOL","Moldova","Moldova");
        case	215	 : result.setValues(215	,"MAL","Malta","MALTA");
        case	216	 : result.setValues(216	,"ARM","Armenia","Armenia");
        case	218	 : result.setValues(218	,"GER","Germany","Germany");
        case	219	 : result.setValues(219	,"DEN","Denmark","Denmark");
        case	220	 : result.setValues(220	,"DEN","Denmark","Denmark");
        case	224	 : result.setValues(224	,"SPA","Spain","Spain");
        case	225	 : result.setValues(225	,"SPA","Spain","Spain");
        case	226	 : result.setValues(226	,"FRA","France","France");
        case	227	 : result.setValues(227	,"FRA","France","France");
        case	228	 : result.setValues(228	,"FRA","France","France");
        case	229	 : result.setValues(229	,"MAL","Malta","Malta");
        case	230	 : result.setValues(230	,"FIN","Finland","Finland");
        case	231	 : result.setValues(231	,"FAR","Faroe Islands","Faro Isle");
        case	232	 : result.setValues(232	,"UKM","United Kingdom","G Britain");
        case	233	 : result.setValues(233	,"UKM","United Kingdom","G Britain");
        case	234	 : result.setValues(234	,"UKM","United Kingdom","G Britain");
        case	235	 : result.setValues(235	,"UKM","United Kingdom","G Britain");
        case	236	 : result.setValues(236	,"GIB","Gibraltar","Gibraltar");
        case	237	 : result.setValues(237	,"GRE","Greece","Greece");
        case	238	 : result.setValues(238	,"CRT","Croatia","Croatia");
        case	239	 : result.setValues(239	,"GRE","Greece","Greece");
        case	240	 : result.setValues(240	,"GRE","Greece","Greece");
        case	241	 : result.setValues(241	,"GRE","Greece","Greece");
        case	242	 : result.setValues(242	,"MOR","Morocco","Morocco");
        case	243	 : result.setValues(243	,"HUN","Hungary","Hungary");
        case	244	 : result.setValues(244	,"NET","Netherlands","Netherland");
        case	245	 : result.setValues(245	,"NET","Netherlands","Netherland");
        case	246	 : result.setValues(246	,"NET","Netherlands","Netherland");
        case	247	 : result.setValues(247	,"ITA","Italy","Italy");
        case	248	 : result.setValues(248	,"MAL","Malta","Malta");
        case	249	 : result.setValues(249	,"MAL","Malta","Malta");
        case	250	 : result.setValues(250	,"IRE","Ireland","Ireland");
        case	251	 : result.setValues(251	,"ICE","Iceland","Iceland");
        case	252	 : result.setValues(252	,"LIE","Liechtenstein","Liechten");
        case	253	 : result.setValues(253	,"LUX","Luxembourg","Luxembourg");
        case	254	 : result.setValues(254	,"MON","Monaco","Monaco");
        case	255	 : result.setValues(255	,"MAE","Madeira","Madeira");
        case	256	 : result.setValues(256	,"MAL","Malta","Malta");
        case	257	 : result.setValues(257	,"NOR","Norway","Norway");
        case	258	 : result.setValues(258	,"NOR","Norway","Norway");
        case	259	 : result.setValues(259	,"NOR","Norway","Norway");
        case	261	 : result.setValues(261	,"POL","Poland","Poland");
        case	262	 : result.setValues(262	,"MNT","Montenegro","Montenegro");
        case	263	 : result.setValues(263	,"POR","Portugal","Portugal");
        case	264	 : result.setValues(264	,"ROM","Romania","Romania");
        case	265	 : result.setValues(265	,"SWE","Sweden","Sweden");
        case	266	 : result.setValues(266	,"SWE","Sweden","Sweden");
        case	267	 : result.setValues(267	,"SLV","Slovak Republic","Slovakia");
        case	268	 : result.setValues(268	,"SAN","San Marino","San Marino");
        case	269	 : result.setValues(269	,"SWT","Switzerland","Swiss");
        case	270	 : result.setValues(270	,"CZH","Czech Republic","Czech Rep");
        case	271	 : result.setValues(271	,"TUR","TÃƒÂ¼rkiye","TÃƒÂ¼rkiye");
        case	272	 : result.setValues(272	,"UKR","Ukraine","Ukraine");
        case	273	 : result.setValues(273	,"RUS","Russian Federation","Russia");
        case	274	 : result.setValues(274	,"MKD","North Macedonia (Republic of)","North Mac");
        case	275	 : result.setValues(275	,"LAT","Latvia","Latvia");
        case	276	 : result.setValues(276	,"EST","Estonia","Estonia");
        case	277	 : result.setValues(277	,"LIT","Lithuania","Lithuania");
        case	278	 : result.setValues(278	,"SVN","Slovenia","Slovenia");
        case	279	 : result.setValues(279	,"SER","Serbia","Serbia");
        case	301	 : result.setValues(301	,"ANA","Anguilla","Anguilla");
        case	303	 : result.setValues(303	,"ALA","Alaska (State of)","Alaska");
        case	304	 : result.setValues(304	,"ANT","Antigua and Barbuda","Antigua");
        case	305	 : result.setValues(305	,"ANT","Antigua and Barbuda","Antigua");
        case	306	 : result.setValues(306	,"NEA","Netherlands Antilles","N Antilles");
        case	307	 : result.setValues(307	,"ARU","Aruba","Aruba");
        case	308	 : result.setValues(308	,"BAA","Bahamas","Bahamas");
        case	309	 : result.setValues(309	,"BAA","Bahamas","Bahamas");
        case	310	 : result.setValues(310	,"BER","Bermuda","Bermuda");
        case	311	 : result.setValues(311	,"BAA","Bahamas","Bahamas");
        case	312	 : result.setValues(312	,"BEZ","Belize","Belize");
        case	314	 : result.setValues(314	,"BAR","Barbados","Barbados");
        case	316	 : result.setValues(316	,"CAN","Canada","Canada");
        case	319	 : result.setValues(319	,"CAY","Cayman Islands","Cayman Is");
        case	321	 : result.setValues(321	,"COS","Costa Rica","Costa Rica");
        case	323	 : result.setValues(323	,"CUB","Cuba","Cuba");
        case	325	 : result.setValues(325	,"DOM","Dominica","Dominica");
        case	327	 : result.setValues(327	,"DOR","Dominican Republic","Dominican");
        case	329	 : result.setValues(329	,"GUA","Guadeloupe","Guadeloupe");
        case	330	 : result.setValues(330	,"GRA","Grenada","Grenada");
        case	331	 : result.setValues(331	,"GRN","Greenland","Greenland");
        case	332	 : result.setValues(332	,"GUT","Guatemala","Guatemala");
        case	334	 : result.setValues(334	,"HON","Honduras","Honduras");
        case	336	 : result.setValues(336	,"HAI","Haiti","Haiti");
        case	338	 : result.setValues(338	,"USA","United States","USA");
        case	339	 : result.setValues(339	,"JAM","Jamaica","Jamaica");
        case	341	 : result.setValues(341	,"SKN","Saint Kitts and Nevis","St Kitts");
        case	343	 : result.setValues(343	,"SLU","Saint Lucia","St Lucia");
        case	345	 : result.setValues(345	,"MEX","Mexico","Mexico");
        case	347	 : result.setValues(347	,"MTQ","Martinique","Martinique");
        case	348	 : result.setValues(348	,"MOT","Montserrat","Montserrat");
        case	350	 : result.setValues(350	,"NIC","Nicaragua","Nicaragua");
        case	351	 : result.setValues(351	,"PAN","Panama","Panama");
        case	352	 : result.setValues(352	,"PAN","Panama","Panama");
        case	353	 : result.setValues(353	,"PAN","Panama","Panama");
        case	354	 : result.setValues(354	,"PAN","Panama","Panama");
        case	355	 : result.setValues(355	,"PAN","Panama","Panama");
        case	356	 : result.setValues(356	,"PAN","Panama","Panama");
        case	357	 : result.setValues(357	,"PAN","Panama","Panama");
        case	358	 : result.setValues(358	,"PUE","Puerto Rico","PuertoRico");
        case	359	 : result.setValues(359	,"ELS","El Salvador","ElSalvador");
        case	361	 : result.setValues(361	,"SPI","St. Pierre and Miquelon","St Pierre");
        case	362	 : result.setValues(362	,"TAT","Trinidad and Tobago","Trinidad");
        case	364	 : result.setValues(364	,"TUK","Turks and Caicos Islands","Caicos Is");
        case	366	 : result.setValues(366	,"USA","United States","USA");
        case	367	 : result.setValues(367	,"USA","United States","USA");
        case	368	 : result.setValues(368	,"USA","United States","USA");
        case	369	 : result.setValues(369	,"USA","United States","USA");
        case	370	 : result.setValues(370	,"PAN","Panama","Panama");
        case	371	 : result.setValues(371	,"PAN","Panama","Panama");
        case	372	 : result.setValues(372	,"PAN","Panama","Panama");
        case	373	 : result.setValues(373	,"PAN","Panama","Panama");
        case	374	 : result.setValues(374	,"PAN","Panama","Panama");
        case	375	 : result.setValues(375	,"SVG","Saint Vincent and the Grenadines","St Vincent");
        case	376	 : result.setValues(376	,"SVG","Saint Vincent and the Grenadines","St Vincent");
        case	377	 : result.setValues(377	,"SVG","Saint Vincent and the Grenadines","St Vincent");
        case	378	 : result.setValues(378	,"BVI","British Virgin Islands","Virgin GB");
        case	379	 : result.setValues(379	,"USV","United States Virgin Islands","Virgin US");
        case	401	 : result.setValues(401	,"AFG","Afghanistan","Afghan");
        case	403	 : result.setValues(403	,"SAU","Saudi Arabia","Saudi");
        case	405	 : result.setValues(405	,"BAN","Bangladesh","Bangladesh");
        case	408	 : result.setValues(408	,"BAH","Bahrain","Bahrain");
        case	410	 : result.setValues(410	,"BHU","Bhutan","Bhutan");
        case	412	 : result.setValues(412	,"CHN","China","China");
        case	413	 : result.setValues(413	,"CHN","China","China");
        case	414	 : result.setValues(414	,"CHN","China","CHINA");
        case	416	 : result.setValues(416	,"TAI","Chinese Taipei","Taipei");
        case	417	 : result.setValues(417	,"SRI","Sri Lanka","Sri Lanka");
        case	419	 : result.setValues(419	,"IND","India","India");
        case	422	 : result.setValues(422	,"IRN","Iran","Iran");
        case	423	 : result.setValues(423	,"AZR","Azerbaijan","Azerbaijan");
        case	425	 : result.setValues(425	,"IRQ","Iraq","Iraq");
        case	428	 : result.setValues(428	,"ISR","Israel","Israel");
        case	431	 : result.setValues(431	,"JPN","Japan","Japan");
        case	432	 : result.setValues(432	,"JPN","Japan","Japan");
        case	434	 : result.setValues(434	,"TKM","Turkmenistan","Turkmenist");
        case	436	 : result.setValues(436	,"KAZ","Kazakhstan","Kazakhstan");
        case	437	 : result.setValues(437	,"UZB","Uzbekistan","Uzbekistan");
        case	438	 : result.setValues(438	,"JOR","Jordan","Jordan");
        case	440	 : result.setValues(440	,"KOR","Korea (Republic of)","Korea Sou");
        case	441	 : result.setValues(441	,"KOR","Korea (Republic of)","Korea Sou");
        case	443	 : result.setValues(443	,"PAA","Palestine","Palestine");
        case	445	 : result.setValues(445	,"KDR","Democratic People's Republic of Korea","Korea Nor");
        case	447	 : result.setValues(447	,"KUW","Kuwait","Kuwait");
        case	450	 : result.setValues(450	,"LEB","Lebanon","Lebanon");
        case	451	 : result.setValues(451	,"KYR","Kyrgyz Republic","Kyrgyzia");
        case	453	 : result.setValues(453	,"MAC","Macao, China","Macao");
        case	455	 : result.setValues(455	,"MAV","Maldives","Maldives");
        case	457	 : result.setValues(457	,"MNG","Mongolia","Mongolia");
        case	459	 : result.setValues(459	,"NEP","Nepal","Nepal");
        case	461	 : result.setValues(461	,"OMN","Oman","Oman");
        case	463	 : result.setValues(463	,"PAK","Pakistan","Pakistan");
        case	466	 : result.setValues(466	,"QAT","Qatar","Qatar");
        case	468	 : result.setValues(468	,"SYR","Syria","Syria");
        case	470	 : result.setValues(470	,"UAE","United Arab Emirates","UAE");
        case	471	 : result.setValues(471	,"UAE","United Arab Emirates","UAE");
        case	472	 : result.setValues(472	,"TJK","Tajikistan","TAJIKISTAN");
        case	473	 : result.setValues(473	,"YEM","Yemen","Yemen");
        case	475	 : result.setValues(475	,"YEM","Yemen","Yemen");
        case	477	 : result.setValues(477	,"HKG","Hong Kong, China","Hong Kong");
        case	478	 : result.setValues(478	,"BOS","Bosnia and Herzegovina","Bosniaherz");
        case	503	 : result.setValues(503	,"AUS","Australia","Australia");
        case	506	 : result.setValues(506	,"BUR","Myanmar","Burma");
        case	508	 : result.setValues(508	,"BRU","Brunei Darussalam","Brunei");
        case	510	 : result.setValues(510	,"MIC","Micronesia","Micronesia");
        case	511	 : result.setValues(511	,"PAL","Palau","Palau");
        case	512	 : result.setValues(512	,"NZL","New Zealand","NewZealand");
        case	514	 : result.setValues(514	,"CMB","Cambodia","Cambodia");
        case	515	 : result.setValues(515	,"CMB","Cambodia","Cambodia");
        case	516	 : result.setValues(516	,"CHR","Christmas Island","Christmas");
        case	518	 : result.setValues(518	,"COO","Cook Islands","Cook Isles");
        case	520	 : result.setValues(520	,"FIJ","Fiji","Fiji");
        case	523	 : result.setValues(523	,"COC","Cocos (Keeling) Islands","Cocos Isle");
        case	525	 : result.setValues(525	,"INO","Indonesia","Indonesia");
        case	529	 : result.setValues(529	,"KIR","Kiribati","Kiribati");
        case	531	 : result.setValues(531	,"LAO","Laos","Lao");
        case	533	 : result.setValues(533	,"MLY","Malaysia","Malaysia");
        case	536	 : result.setValues(536	,"MAI","Northern Mariana Islands","Mariana Is");
        case	538	 : result.setValues(538	,"MAR","Marshall Islands","Marshall I");
        case	540	 : result.setValues(540	,"NCA","New Caledonia","Caledonia");
        case	542	 : result.setValues(542	,"NIU","Niue","Niue Isle");
        case	544	 : result.setValues(544	,"NAU","Nauru","Nauru");
        case	546	 : result.setValues(546	,"PLY","French Polynesia","Polynesia");
        case	548	 : result.setValues(548	,"PHI","Philippines","Philippine");
        case	550	 : result.setValues(550	,"TIM","Timor-Leste (Democratic Republic of)","TimorLeste");
        case	553	 : result.setValues(553	,"PAP","Papua New Guinea","Papua NG");
        case	555	 : result.setValues(555	,"PIT","Pitcairn","Pitcairn I");
        case	557	 : result.setValues(557	,"SOL","Solomon Islands","Solomon Is");
        case	559	 : result.setValues(559	,"ASA","American Samoa","Samoa USA");
        case	561	 : result.setValues(561	,"WSA","Samoa","West Samoa");
        case	563	 : result.setValues(563	,"SIN","Singapore","Singapore");
        case	564	 : result.setValues(564	,"SIN","Singapore","Singapore");
        case	565	 : result.setValues(565	,"SIN","Singapore","Singapore");
        case	566	 : result.setValues(566	,"SIN","Singapore","SINGAPORE");
        case	567	 : result.setValues(567	,"THA","Thailand","Thailand");
        case	570	 : result.setValues(570	,"TON","Tonga","Tonga");
        case	572	 : result.setValues(572	,"TUV","Tuvalu","Tuvalu Is");
        case	574	 : result.setValues(574	,"VIE","Vietnam","Vietnam");
        case	576	 : result.setValues(576	,"VAN","Vanuatu","Vanuatu");
        case	577	 : result.setValues(577	,"VAN","Vanuatu","Vanuatu");
        case	578	 : result.setValues(578	,"WAL","Wallis and Futuna Islands","Wallis Is");
        case	601	 : result.setValues(601	,"SAF","South Africa","So Africa");
        case	603	 : result.setValues(603	,"ANG","Angola","Angola");
        case	605	 : result.setValues(605	,"ALG","Algeria","Algeria");
        case	607	 : result.setValues(607	,"SPL","Saint Paul and Amsterdam Islands","St Paul");
        case	608	 : result.setValues(608	,"ASC","Ascension Island","Ascension");
        case	609	 : result.setValues(609	,"BUI","Burundi","Burundi");
        case	610	 : result.setValues(610	,"BEN","Benin","Benin");
        case	611	 : result.setValues(611	,"BOT","Botswana","Botswana");
        case	612	 : result.setValues(612	,"CAR","Central African Republic","CenAfr Rep");
        case	613	 : result.setValues(613	,"CAM","Cameroon","Cameroon");
        case	615	 : result.setValues(615	,"CON","Congo","Congo");
        case	616	 : result.setValues(616	,"COM","Comoros","Comoros");
        case	617	 : result.setValues(617	,"CAP","Cape Verde","Cape Verde");
        case	618	 : result.setValues(618	,"CRP","Crozet Archipelago","Crozet");
        case	619	 : result.setValues(619	,"IVO","Ivory Coast","IvoryCoast");
        case	620	 : result.setValues(620	,"COM","Comoros","Comoros");
        case	621	 : result.setValues(621	,"DJI","Djibouti","Djibouti");
        case	622	 : result.setValues(622	,"EGY","Egypt","Egypt");
        case	624	 : result.setValues(624	,"ETH","Ethiopia","Ethiopia");
        case	625	 : result.setValues(625	,"ERT","Eritrea","Eritrea");
        case	626	 : result.setValues(626	,"GAB","Gabon","Gabon Rep");
        case	627	 : result.setValues(627	,"GHA","Ghana","Ghana");
        case	629	 : result.setValues(629	,"GAM","Gambia","Gambia");
        case	630	 : result.setValues(630	,"GUB","Guinea-Bissau","Guinea Bis");
        case	631	 : result.setValues(631	,"EQG","Equatorial Guinea","Eq Guinea");
        case	632	 : result.setValues(632	,"GUN","Guinea","Guinea Rep");
        case	633	 : result.setValues(633	,"BUF","Burkina Faso","Burkina FS");
        case	634	 : result.setValues(634	,"KEN","Kenya","Kenya");
        case	635	 : result.setValues(635	,"KER","Kerguelen Islands","Kerguelen");
        case	636	 : result.setValues(636	,"LIB","Liberia","Liberia");
        case	637	 : result.setValues(637	,"LIB","Liberia","Liberia");
        case	638	 : result.setValues(638	,"SSD","South Sudan","Southsudan");
        case	642	 : result.setValues(642	,"LBY","Libya","Libya");
        case	644	 : result.setValues(644	,"LES","Lesotho","Lesotho");
        case	645	 : result.setValues(645	,"MAU","Mauritius","Mauritius");
        case	647	 : result.setValues(647	,"MAD","Madagascar","Madagascar");
        case	649	 : result.setValues(649	,"MLI","Mali","Mali");
        case	650	 : result.setValues(650	,"MOZ","Mozambique","Mozambique");
        case	654	 : result.setValues(654	,"MAA","Mauritania","Mauritania");
        case	655	 : result.setValues(655	,"MAW","Malawi","Malawi");
        case	656	 : result.setValues(656	,"NIG","Niger","Niger");
        case	657	 : result.setValues(657	,"NIA","Nigeria","Nigeria");
        case	659	 : result.setValues(659	,"NAM","Namibia","Namibia");
        case	660	 : result.setValues(660	,"REU","Reunion (also same country code for Mayotte)","Reunion");
        case	661	 : result.setValues(661	,"RWA","Rwanda","Rwanda");
        case	662	 : result.setValues(662	,"SUD","Sudan","Sudan");
        case	663	 : result.setValues(663	,"SEN","Senegal","Senegal");
        case	664	 : result.setValues(664	,"SEY","Seychelles","Seychelle");
        case	665	 : result.setValues(665	,"SHE","St. Helena","St Helena");
        case	666	 : result.setValues(666	,"SOM","Somalia","Somali");
        case	667	 : result.setValues(667	,"SIL","Sierra Leone","Sierra Leo");
        case	668	 : result.setValues(668	,"SAO","Sao Tome and Principe","Sao Tome");
        case	669	 : result.setValues(669	,"SWZ","Eswatini","Eswatini");
        case	670	 : result.setValues(670	,"CHA","Chad","Chad");
        case	671	 : result.setValues(671	,"TOG","Togo","Togo");
        case	672	 : result.setValues(672	,"TUN","Tunisia","Tunisia");
        case	674	 : result.setValues(674	,"TAN","Tanzania","Tanzania");
        case	675	 : result.setValues(675	,"UGA","Uganda","Uganda");
        case	676	 : result.setValues(676	,"ZAI","Democratic Republic of the Congo","Zaire");
        case	677	 : result.setValues(677	,"TAN","Tanzania","Tanzania");
        case	678	 : result.setValues(678	,"ZAM","Zambia","Zambia");
        case	679	 : result.setValues(679	,"ZIM","Zimbabwe","Zimbabwe");
        case	701	 : result.setValues(701	,"ARG","Argentina","Argentina");
        case	710	 : result.setValues(710	,"BRA","Brazil","Brazil");
        case	720	 : result.setValues(720	,"BOL","Bolivia","Bolivia");
        case	725	 : result.setValues(725	,"CHI","Chile","Chile");
        case	730	 : result.setValues(730	,"COL","Colombia","Colombia");
        case	735	 : result.setValues(735	,"ECU","Ecuador","Ecuador");
        case	740	 : result.setValues(740	,"FAL","Falkland Islands (Malvinas)","Falkland I");
        case	745	 : result.setValues(745	,"GUI","Guiana (French Dept. Of)","Guiana");
        case	750	 : result.setValues(750	,"GUY","Guyana","Guyana");
        case	755	 : result.setValues(755	,"PAR","Paraguay","Paraguay");
        case	760	 : result.setValues(760	,"PER","Peru","Peru");
        case	765	 : result.setValues(765	,"SUR","Suriname","Suriname");
        case	770	 : result.setValues(770	,"URU","Uruguay","Uruguay");
        case	775	 : result.setValues(775	,"VEN","Venezuela","Venezuela");
        default : result.setValues(code,"UNK","Unknown country code","Unkown");
        return result;
    }
}